AZURE_OPENAI_SYSTEM_MESSAGE:
  - "Mensaje sistema 1"
  - "Mensaje sistema 2"

AZURE_OPENAI_TEMPERATURE:
  type: float
  min: 0.0
  max: 1.0

AZURE_OPENAI_TOP_P:
  type: float
  min: 0.0
  max: 1.0

AZURE_OPENAI_MAX_TOKENS:
  type: int
  min: 10
  max: 16384

AZURE_SEARCH_STRICTNESS:
  type: int
  min: 0
  max: 5

AZURE_SEARCH_TOP_K:
  type: int
  min: 0
  max: 1000
